## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
    #  - STATEFUL-APP-DEPLOY
    #  - APP-FUNC-TEST
    #  - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

## Setup the kubernetes cluster

aws-cluster:
  image: atulabhi/kops:v8
  stage: CLUSTER-SETUP 
  script: 
    - ./script/aws
  artifacts:
    paths:
      - aws/

## Setup OpenEBS control plane

openebs-aws-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script: 
   - ./script/provider/infra-setup
   - ./script/provider/infra-setup-sc
  artifacts:
    paths:
      - aws-openebs/

## Define a job template for app deployers

        #.app_deploy_template:
        #  image: atulabhi/kops:v8
        #  stage: STATEFUL-APP-DEPLOY 
        #  dependencies:
        #    - openebs-aws-deploy
        #  artifacts:
        #    paths: 
        #      - aws-openebs/

## Define the app deployer jobs

## PERCONA-JIVA
#percona-jiva-run/load/check 0:2:
#  extends: .app_deploy_template
#  script: 
#   - ./script/apps/percona/deployer/percona-app-deploy-jiva

        #percona-jiva-run/load/check 1:2:
        #  extends: .app_deploy_template
        #  before_script: 
        #   - sleep 180
        #  script: 
        #   - ./script/apps/percona/workload/jiva/percona-app-workload-jiva

## MONGO-JIVA
#mongo-jiva-run/load/check 0:2:
# extends: .app_deploy_template
# script: 
#  - ./script/apps/mongo/deployer/mongo-app-deploy-jiva

        #mongo-jiva-run/load/check 1:2:
        #  extends: .app_deploy_template
        #  before_script: 
        #   - sleep 180
        #  script: 
        #   - ./script/apps/mongo/workload/jiva/mongo-app-workload-jiva

# POSTGRES-JIVA
#postgres-jiva-run/load/check 0:2:
# extends: .app_deploy_template
# script: 
#  - ./script/apps/postgres/deployer/postgres-app-deploy-jiva

        #postgres-jiva-run/load/check 1:2:
        #  extends: .app_deploy_template
        #  before_script: 
        #   - sleep 180
        #  script: 
        #   - ./script/apps/postgres/workload/jiva/postgres-app-workload-jiva

# CASSANDRA-JIVA
#cassandra-jiva-run/load/check 0:2:
# extends: .app_deploy_template
# script: 
#  - ./script/apps/cassandra/deployer/cassandra-app-deploy-jiva

        #cassandra-jiva-run/load/check 1:2:
        #  extends: .app_deploy_template
        #  before_script: 
        #   - sleep 180
        #  script: 
        #   - ./script/apps/cassandra/workload/jiva/cassandra-app-workload-jiva

# JENKINS-JIVA

cleanup-aws:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - aws-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/aws-cleanup
    - ./script/aws-cleanup
